# **Business Understanding**

**About Data:**
Derived from simple hierarchical decision model, this database may be useful for testing constructive induction and structure discovery methods.

Additional Information

Car Evaluation Database was derived from a simple hierarchical decision model originally developed for the demonstration of DEX, M. Bohanec, V. Rajkovic: Expert system for decision making. Sistemica 1(1), pp. 145-157, 1990.). The model evaluates cars according to the following concept structure:

CAR                      car acceptability
. PRICE                  overall price
. . buying               buying price
. . maint                price of the maintenance
. TECH                   technical characteristics
. . COMFORT              comfort
. . . doors              number of doors
. . . persons            capacity in terms of persons to carry
. . . lug_boot           the size of luggage boot
. . safety               estimated safety of the car

Input attributes are printed in lowercase. Besides the target concept (CAR), the model includes three intermediate concepts: PRICE, TECH, COMFORT. Every concept is in the original model related to its lower level descendants by a set of examples (for these examples sets see http://www-ai.ijs.si/BlazZupan/car.html).

The Car Evaluation Database contains examples with the structural information removed, i.e., directly relates CAR to the six input attributes: buying, maint, doors, persons, lug_boot, safety.

Because of known underlying concept structure, this database may be particularly useful for testing constructive induction and structure discovery methods.

Bohanec, M. (1988). Car Evaluation [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C5JP48.

[Data Source](https://archive.ics.uci.edu/dataset/19/car+evaluation)

#### **Loading Library**

In [21]:
import pandas as pd

#### **Loading Data**

In [22]:
columns = ["buying", "maint", "doors","persons","lug_boot","safety", "class"]

In [23]:
df = pd.read_csv("data/car.data",names=columns)

In [24]:
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [25]:
df.tail()

     buying maint  doors persons lug_boot safety  class
1723    low   low  5more    more      med    med   good
1724    low   low  5more    more      med   high  vgood
1725    low   low  5more    more      big    low  unacc
1726    low   low  5more    more      big    med   good
1727    low   low  5more    more      big   high  vgood

#### **Getting the dimensions of the data**

In [26]:
rows, columns= df.shape
output =f"{columns} features and {rows} records"
print(output)

7 features and 1728 records

#### **Get a summary of the structure of the table**

- data types
- Non nulll value counts
- Memory usage

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   str
 1   maint     1728 non-null   str
 2   doors     1728 non-null   str
 3   persons   1728 non-null   str
 4   lug_boot  1728 non-null   str
 5   safety    1728 non-null   str
 6   class     1728 non-null   str
dtypes: str(7)
memory usage: 94.6 KB

![image.png](screen-shots/car_variable_definiton_table.png)

In [28]:
df.rename(columns={'buying': 'buyingPrice'}, inplace=True)
df.rename(columns={'maint': 'priceofMaintenance'}, inplace=True)
df.rename(columns={'lug_boot': 'sizeLuggageBoot'}, inplace=True)
df.rename(columns={'safety': 'estimatedCarSafety'}, inplace=True)
df.rename(columns={'persons': 'carPassengerCapacity'}, inplace=True) 
df.rename(columns={'doors': 'numberOfdoors'}, inplace=True)

In [29]:
df.describe() # statistical summary

,buyingPrice,priceofMaintenance,numberOfdoors,carPassengerCapacity,sizeLuggageBoot,estimatedCarSafety,class
count,1728,1728,1728,1728,1728,1728,1728
unique,4,4,4,3,3,3,4
top,vhigh,vhigh,2,2,small,low,unacc
freq,432,432,432,576,576,576,1210

In [33]:
df [["buyingPrice","priceofMaintenance"]].describe() # statistical summary

       buyingPrice priceofMaintenance
count         1728               1728
unique           4                  4
top          vhigh              vhigh
freq           432                432

In [34]:
high_end_vehicleS_df = df[df["buyingPrice"] == df["priceofMaintenance"]]

In [35]:
high_end_vehicleS_df.shape

(432, 7)

In [43]:
numbers = (1,2,3,4,5,6,7,8,9,10) # data swithout an outlier
numbers = (5,5,5,5,5,6,7,8,9,10) # data  without an outlier
# data with an outlier
numbers = (5,5,5,5,5,6,7,8,9,100) # data  without an outlier

total = lambda x: sum(numbers)
n = len(numbers) # size of observation
mean = total(numbers)/n
print(f"TOTAL: {total(numbers)} , SIZE: {n}, DATA: {numbers}")
print(f"Satisfaction level: {mean}")

TOTAL: 155 , SIZE: 10, DATA: (5, 5, 5, 5, 5, 6, 7, 8, 9, 100)
Satisfaction level: 15.5

# **Data Understanding**

# **Data Preparation**

# **Modeling**

# **Evaluation**

# **Deployment**